services:
  - type: web
    name: document-signing-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
